language: node_js
node_js:
  - '9'

# Cache npm inbetween builds to improve build time
# Documentaion - https://docs.travis-ci.com/user/caching/
cache:
  yarn: true
  directories:
  - node_modules # NPM packages